// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfwiyoxdzhmfyzpsgpmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmd2l5b3hkemhtZnl6cHNncG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzc4OTAsImV4cCI6MjA2MzkxMzg5MH0.XNLg36KVjTSwVWU40-mnkrFGm3vD4WHpB4F29KtYij0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);